### ISSUE TITLE
bad argument #3 to setOpposite in jbulx-guardban.lua

### ISSUE THREAD

**Issue by AceTheGmodGeek** [IanMurray/ULX-commands-for-Jailbreak-7#1]
I have added this addon for the Guard Banning, however, the guard banning function isn't working, I'm getting this error:

[ERROR] bad argument #3 to ULib.cmds.TranslateCommand:setOpposite (nil,string expected, got table)
  1. error - [C]:-1
   2. checkArg - addons/ulib/lua/ulib/shared/misc.lua:520
    3. setOpposite - addons/ulib/lua/ulib/shared/commands.lua:1142
     4. unknown - addons/ulx/lua/ulx/modules/sh/jbulx-guardban.lua:33
      5. include - [C]:-1
       6. unknown - addons/ulx/lua/ulx/cl_init.lua:17
        7. include - [C]:-1
         8. unknown - addons/ulx/lua/ulib/modules/ulx_init.lua:4
          9. include - [C]:-1
           10. unknown - addons/ulib/lua/ulib/cl_init.lua:23
            11. include - [C]:-1
             12. unknown - addons/ulib/lua/autorun/ulib_init.lua:5

**Comment by AceTheGmodGeek** [comment]
I fixed that error; however, I have another error where the unguardban command isnt working

**Comment by 7bitlyrus** [comment]
I'm believe they maybe have been some changes since the last time I've used this addon myself. Try changing [this line](https://github.com/IanMurray/ulx-commands-for-jailbreak-7/blob/master/lua/ulx/modules/sh/jbulx-guardban.lua#L34) from 
```lua
guardban:setOpposite( "ulx unguardban", { _, _, true }, {"!unguardban", "!guardunban"} )
```
to:
```lua
guardban:setOpposite( "ulx unguardban", { _, _, true }, "!unguardban")

**Comment by AceTheGmodGeek** [comment]
Ah, thanks that fixed it! I have another question, is there a way to set a time for the ban? Instead of only having it only be 960 minutes?

**Comment by 7bitlyrus** [comment]
Great!

I wrote this command for my own servers and never really expected for it to be used to be honest.

However, you can change [Line 16](https://github.com/IanMurray/ulx-commands-for-jailbreak-7/blob/master/lua/ulx/modules/sh/jbulx-guardban.lua#L16) to change the time, specified in seconds.

For example:
```lua
target_ply:SetPData( "guardbanned", os.time()+57600 ) -- 57600 sec =  960 minutes (16 hours)
target_ply:SetPData( "guardbanned", os.time()+86400 ) -- 86400 sec = 1440 minutes (24 hours)
-- etc...
```

**Comment by AceTheGmodGeek** [comment]
Hey, not to disturb you anymore, but is it possible to add a variable for a time? So the admin can pick how long? If you are busy, or can't help, It's fine, as this is going beyond.
Sorry for the inconvience

**Comment by 7bitlyrus** [comment]
Create a new issue and I'll be glad to when I get around to it!

**Comment by 7bitlyrus** [comment]
I'm actually reopening this, because I'd like to fix this if it happens on a bare-bones server. Are you (or anyone else) able to replicate this on a clean server with only ULX, ULib, Jailbreak & this addon installed?

**Comment by AceTheGmodGeek** [comment]
I'll test it out soon for you, I'll create a test server.

**Comment by 7bitlyrus** [comment]
Cannot Reproduce. Using latest versions of ULX, ULib, Jailbreak & this addon.

**Comment by VulpusMaximus** [comment]
It seems likely that this was an older version of ULX/ULib that was unable to handle tables for arguments, like the one used for allowing different chat command aliases.
