### ISSUE TITLE
Warden ban command.

### ISSUE THREAD

**Issue by Pertin** [IanMurray/ULX-commands-for-Jailbreak-7#3]
Bans the player from warden instead of banning them from guards completely.

**Comment by VulpusMaximus** [comment]
I have added this to my fork, currently testing it, but it should work or be easy to fix

**Comment by 7bitlyrus** [comment]
The primary reason I had never added this feature was due to the warden
notification me being burnt out on Garry's Mod. However, I believe in
collaborative benefits of open source communities and would welcome a pull
request of a semi-polished or polished feature!

**Comment by VulpusMaximus** [comment]
At the moment I am polishing off the merged fork by pepeisdatboi and fixing small issues, but the wardenban should be published soon, within the next couple of days at most.

**Comment by VulpusMaximus** [comment]
I have added a working wardenban to my fork, if you are still interested, along with other features.

**Comment by VulpusMaximus** [comment]
Added and merged into main.
