### ISSUE TITLE
Repository Transfer Request

### ISSUE THREAD

**Issue by VulpusMaximus** [IanMurray/ULX-commands-for-Jailbreak-7#5]
From what I understand from your reply to #3 , you don't seem interested in continuing development on this project. If this is true, I would like to propose a repository transfer to me, so I can continue on its development directly, and allow users to easily find more updated versions of this addon. If you are not up for this, I am fine with that and will simply add in a pull request to merge my changes into your master for this, but if you aren't continuing to work on this, I would like to take it over so I can continue it myself without constant pull requests to you every time I add a new feature, fix things, etc.

**Comment by VulpusMaximus** [comment]
I have added a pull request to merge my fork into the main.

**Comment by VulpusMaximus** [comment]
An alternative could be to create an organisation for JBULX development and transfer this repository to the organisation.

**Comment by 7bitlyrus** [comment]
Send me an email at ian@murr.pro or add me on discord, Lyrus#5555, and we'll discuss in private.

**Comment by VulpusMaximus** [comment]
Added you on Discord, it's quicker and easier than email.
